# -*- coding: utf-8 -*-
"""TF_IDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mSwZaIdPPMwm5u7n6Net-XnahofyK3Lk
"""

import pandas as pd
import joblib
import numpy as np
import joblib

df = pd.read_csv("not_mine.csv")

#df = df[df["category"] != "Other"]

def clean_text(text):
  text = str(text).lower().strip()
  text = text.replace("\xa0", " ")
  return text
df['headline'] = df['headline'].apply(clean_text)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['headline'],
    df['category'],
    test_size=0.2,
    random_state=42,
    stratify=df['category'],
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,     # cap vocabulary size
    ngram_range=(1, 2),     # unigrams + bigrams (captures phrases like "cyclone alert")
    min_df=2       # ignore words that appear in only 1 headline
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

''' from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer for Bag-of-Words model
bow_vectorizer = CountVectorizer(
    max_features=20000,     # cap vocabulary size
    ngram_range=(1, 2),     # unigrams + bigram
    min_df=2                # ignore words that appear in only 1 headline
)

# Fit and transform on training data
X_train_bow = bow_vectorizer.fit_transform(X_train)
# Transform test data
X_test_bow = bow_vectorizer.transform(X_test)

print("Shape of X_train_bow:", X_train_bow.shape)
print("Shape of X_test_bow:", X_test_bow.shape) '''

''' from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train_tfidf, y_train) '''

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train_tfidf, y_train)

''' from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 300,random_state = 0)
classifier.fit(X_train_tfidf, y_train) '''

from sklearn.metrics import classification_report, confusion_matrix

y_pred = classifier.predict(X_test_tfidf.toarray())

print("Classification Report:\n")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

results_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
display(results_df)

unlabelled_df = pd.read_csv("unlabelled_news.csv") # Replace 'unlabelled_news.csv' with your actual unlabelled dataset file name

unlabelled_df['text'] = unlabelled_df['text'].apply(clean_text)

X_unlabelled_tfidf = vectorizer.transform(unlabelled_df['text'])

unlabelled_predictions = classifier.predict(X_unlabelled_tfidf)

unlabelled_df['predicted_category'] = unlabelled_predictions
display(unlabelled_df.head())

import joblib

# assuming you have these two objects after training:
# vectorizer = TfidfVectorizer(...)  -> fitted on your text
# model = LogisticRegression(...)    -> fitted on the TF-IDF vectors

joblib.dump(vectorizer, "tfidf_vectorizer.joblib")
joblib.dump(classifier, "logistic_model.joblib")